### ISSUE TITLE
Confirm Link Duplication

### ISSUE THREAD

**Issue by christohill** [symbiote/silverstripe-memberprofiles#140]
In the 2.0 branch the following code creates a broken link for the confirmation email:

```
'$ConfirmLink'    => Controller::join_links(
    $absoluteBaseURL,
    $this->page->Link('confirm'),
    $this->member->ID,
    "?key={$this->member->ValidationKey}"
),
```
Examples:
`$absoluteBaseURL` returns `http://localhost/myapp/`
`$this->page->Link('confirm')` returns `myapp/registration/`

This makes the link `http://localhost/myapp/myapp/registration/confirm/1?key=123`

Now, I'm testing this in a subfolder on a local environment so is this intentional for a live environment? Or can we use `$this->page->AbsoluteLink('confirm')` for both? If so, I can make a PR for this.

**Comment by nglasl** [comment]
The above has been merged, so closing this. Thanks again for the PR.
