### ISSUE TITLE
Saving fields error on 4.2.1

### ISSUE THREAD

**Issue by liamchowneydev** [symbiote/silverstripe-memberprofiles#148]
When you edit and save a field for example Blog Profile Image I get redirected to this page

http://mydomain.com/SilverStripe/Forms/FormRequestHandler

**Comment by nglasl** [comment]
Hi @liamchowneydev, could you please provide some more detail here? Perhaps some steps on how it can be reproduced?

**Comment by nglasl** [comment]
I remember giving this one a test back when I first commented, however I couldn't replicate this. As per https://github.com/symbiote/silverstripe-memberprofiles/issues/147, I assume it'll be hard to dig up steps to replicate it. This feels like a custom implementation (perhaps the blog module) getting in the way. In which case, I'm going to close this until we have further information on how it can be encountered.
