### ISSUE TITLE
Remove BCC option

### ISSUE THREAD

**Issue by martinduparc** [symbiote/silverstripe-memberprofiles#149]
This is related to https://github.com/symbiote/silverstripe-memberprofiles/pull/46 and the fact that sending emails without a `to` address sometimes fails. An possible solution would be to send individual emails instead of using BCC. I would be happy to create a PR if this is an acceptable fix.

https://github.com/symbiote/silverstripe-memberprofiles/blob/master/src/Pages/MemberProfilePageController.php#L602

CC @gingin77

**Comment by nglasl** [comment]
Hi @martinduparc this seems reasonable to me. Please put a PR through when you can.

**Comment by martinduparc** [comment]
Thanks, @nglasl. The PR is https://github.com/symbiote/silverstripe-memberprofiles/pull/155

**Comment by nglasl** [comment]
Closing this as per https://github.com/symbiote/silverstripe-memberprofiles/pull/155.
