### ISSUE TITLE
Can't sort fields

### ISSUE THREAD

**Issue by altwohill** [symbiote/silverstripe-memberprofiles#154]
I'm wanting to have my membership form in a "natural order".
EG I have additional fields "Title" and "Postnominals" 

These fields appear at the top of the registration form, whilst the "First Name" and "Surname" fields are at the bottom.

I've tried overriding as per this code with no success 

```php

public function updateMemberFormFields(FieldList $fields)
    {
        $firstName = $fields->dataFieldByName('FirstName');
        $fields->removeByName('FirstName');
        $fields->insertAfter('Title', $firstName);
    }

```

**Comment by altwohill** [comment]
As a note I found a workaround: manually adjusting `Sort` in the `MemberProfileField` and `MemberProfileField_Live` tables. Perhaps the membership page gridfield could have a sortable component added to it?

**Comment by nglasl** [comment]
I'm going to close this as it should already support sorting (as above). If this doesn't happen to support sorting (i.e. this is a different gridfield), please let me know and we can re-open this accordingly.
