### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by kenlog** [symbiote/silverstripe-memberprofiles#159]
Hi @nglasl, I'm Italian mother tongue.I would like to deal with the Italian translation, but I can't find the form by searching on the transifex website. Do you accept a pull request? Thank you.

**Comment by nglasl** [comment]
Hi @kenlog, we'd most definitely accept a pull request :)

**Comment by kenlog** [comment]
Hi @nglasl well then I send a pull request :+1:
