### ISSUE TITLE
Fix-4-3-0 branch? 

### ISSUE THREAD

**Issue by altwohill** [symbiote/silverstripe-memberprofiles#160]
Is there any reason the [fix-4-3-0 branch](https://github.com/symbiote/silverstripe-memberprofiles/tree/fix-4-3-0)  isn't merged into the main release?

**Comment by nglasl** [comment]
Hi @altwohill this has been merged through, however the branch wasn't cleaned up at the time https://github.com/symbiote/silverstripe-memberprofiles/pull/157. This branch has now been removed.
