### ISSUE TITLE
Suddenly an error: Please implement getDefaultTitle()

### ISSUE THREAD

**Issue by Artem-Schander** [symbiote/silverstripe-memberprofiles#164]
Hi,

many thanks for this extension.
I think it's somehow my fault, but I have no idea what I could have done wrong. In fact I think i changed just frontend stuff :/
How ever .. I'm getting the following error:

```
[Emergency] Uncaught Exception: Please implement getDefaultTitle() on {get_class(Symbiote\MemberProfiles\Model\MemberProfileSection)}.
GET /admin/pages/edit/show/46
Line 102 in /var/www/html/vendor/symbiote/silverstripe-memberprofiles/src/Model/MemberProfileSection.php
```

It would be nice if someone could help me to solve this :)

Ps.:
It worked some time ago

**Comment by Artem-Schander** [comment]
The comment in the corresponding method says "Returns the title for this profile section. You must implement this in subclasses."
But as far as i know, there are no subclasses.

**Comment by buffy999** [comment]
i'm getting the same issue as well, just can't seem to work out why, it was fine with SS4.2.1 version, it just the issue i'm getting with the SS4.4.1 and SS4.4.3 versions for Memberprofiles 3.0. I might try test this version 4.0.3, hopefully that may resolve the issue. Are you using the 4.0.3 version or??

Some thing must've changed somewhere that is causing this error:
[Emergency] Uncaught Exception: Please implement getDefaultTitle() on {get_class(Symbiote\MemberProfiles\Model\MemberProfileSection)}.

**Comment by buffy999** [comment]
I've just tested the Memberprofiles 4.0.3 with SS4.4.3 in composer.json:
"symbiote/silverstripe-memberprofiles": "^4.0"

It works okay now. You might want to try these versions, may work okay for you. Hope helps. :D

**Comment by buffy999** [comment]
Okay i've found the problem as i've been checking through the codes, on this file here:
/vendor/symbiote/silverstripe-memberprofiles/src/Pages/MemberProfilePage.php

This code has been removed on line 10:
use Symbiote\MemberProfiles\Model\MemberProfileSection;

It now using this instead (on line 9 already there):
use Symbiote\MemberProfiles\Model\MemberProfileFieldsSection;

Which means you will need to replace your code in $has_many array:
private static $has_many = array (
        'Fields'   => MemberProfileField::class,
        'Sections' => MemberProfileFieldsSection::class   <-----
);

Hope this helps.

**Comment by Artem-Schander** [comment]
Thank you @buffy999
