### ISSUE TITLE
Default jquery is breaking sites

### ISSUE THREAD

**Issue by Firesphere** [symbiote/silverstripe-memberprofiles#166]
A site with an existing jquery inclusion, breaks due to the double inclusion of jquery

**Comment by nglasl** [comment]
I'm not sure if there's a simple way around this actually. If it's already being included, we likely want to stick with that version and not add another into the requirements. But, we need a way to detect that (and it may not always come from the requirements). Taking a step back, it seems like the JS for this module could do with a fresh coat of paint so it doesn't even need the dependency.
