### ISSUE TITLE
Contributing link not working

### ISSUE THREAD

**Issue by StevenLantinga** [symbiote/silverstripe-memberprofiles#171]
When I click on the "Contributing" link I am send to a page with the link https://www.symbiote.com.au/contributing-open-source but that link does not work anymore. Therefor it is unclear how to contribute to this project.

**Comment by nglasl** [comment]
Hi @StevenLantinga. Can you please give that link another try? The past couple of months we have been transitioning to a new website, so unfortunately some of the links may have disappeared while that was happening, but I can confirm it's working correctly for me at the moment.

**Comment by StevenLantinga** [comment]
@nglasl Thanks for your reply. The link is working again!

**Comment by nglasl** [comment]
If you have any other questions about contributing, please let me know :smile:
