### ISSUE TITLE
Uncaught ReflectionException: Class EditProfilePage does not exist 

### ISSUE THREAD

**Issue by ruiisidro** [symbiote/silverstripe-memberprofiles#85]
When using this module with "silverstripe-gridfield-betterbuttons" by unclecheese in  the CMS security tab, when trying to edit a user details, silverstripe issues this exception and it's not possible to edit the user details.

**Comment by nyeholt** [comment]
I'm running the latest versions of both modules, and not experiencing any issues; is this still occurring ?

**Comment by silbinarywolf** [comment]
Closed due to no reply + This class does not exist in this module.
